In [1]:
import torch

In [7]:
#dot is used to indicate floating point 
t1 = torch.tensor(4.)
t1.dtype

torch.float32

In [9]:
#Making a vector
t2 = torch.tensor([1., 2, 3, 4])
t2
#Note that all values in a tensor must be of the same type

tensor([1., 2., 3., 4.])

In [12]:
#Making a matrix
t3 = torch.tensor([
                    [5., 6, 7],
                    [8, 9, 10],
                    [11, 12, 13]])
t3

tensor([[ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.]])

In [16]:
#Making a 3-D array

t4 = torch.tensor([
                [
                    [5., 6, 7],
                    [8, 9, 10],
                    [11, 12, 13]
                ],
                [
                    [14., 15, 16],
                    [17, 18, 19],
                    [20, 21, 122]
                ]])
t4

#You cannot make a tensor of an invalid size  

tensor([[[  5.,   6.,   7.],
         [  8.,   9.,  10.],
         [ 11.,  12.,  13.]],

        [[ 14.,  15.,  16.],
         [ 17.,  18.,  19.],
         [ 20.,  21., 122.]]])

In [17]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)


torch.Size([])
torch.Size([4])
torch.Size([3, 3])
torch.Size([2, 3, 3])


In [18]:
#The parameter requires_grad allows you to automatically compute the derivative of a tensor w.r.t those tensors that have this 
#parameter set to true 

x = torch.tensor(3.)
y = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, y, b


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [22]:
w = x * y + b
w
w.backward()

In [23]:
print("dw/dx = {}", x.grad)
print("dw/dy = {}", y.grad)
print("dw/db = {}", b.grad)

#Note that the gradient of tensor x is None b/c we did not say requiring the gradient was necessary

dw/dx = {} None
dw/dy = {} tensor(9.)
dw/db = {} tensor(3.)


In [25]:
#Create a tensor of a given dimension with a given value for each entry
t6 = torch.full([3, 4, 5], 7)
t6

tensor([[[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]],

        [[7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7],
         [7, 7, 7, 7, 7]]])

In [29]:
#How to concatenate two different tensors
t7 = torch.cat((t4, t4))
t7, t7.shape

(tensor([[[  5.,   6.,   7.],
          [  8.,   9.,  10.],
          [ 11.,  12.,  13.]],
 
         [[ 14.,  15.,  16.],
          [ 17.,  18.,  19.],
          [ 20.,  21., 122.]],
 
         [[  5.,   6.,   7.],
          [  8.,   9.,  10.],
          [ 11.,  12.,  13.]],
 
         [[ 14.,  15.,  16.],
          [ 17.,  18.,  19.],
          [ 20.,  21., 122.]]]),
 torch.Size([4, 3, 3]))

In [30]:
#There are thounsands of operations you can perform on every element of a tensor, like taking the sine of the value in a cell
t8 = torch.sin(t7)
t8

tensor([[[-0.9589, -0.2794,  0.6570],
         [ 0.9894,  0.4121, -0.5440],
         [-1.0000, -0.5366,  0.4202]],

        [[ 0.9906,  0.6503, -0.2879],
         [-0.9614, -0.7510,  0.1499],
         [ 0.9129,  0.8367,  0.4987]],

        [[-0.9589, -0.2794,  0.6570],
         [ 0.9894,  0.4121, -0.5440],
         [-1.0000, -0.5366,  0.4202]],

        [[ 0.9906,  0.6503, -0.2879],
         [-0.9614, -0.7510,  0.1499],
         [ 0.9129,  0.8367,  0.4987]]])

In [36]:
#You can reshape a tensor to be higher or lower dimensional than your original one, so long as they number of elements remains constant
t9 = t8.reshape(2, 2, 3, 3)
t9

tensor([[[[-0.9589, -0.2794,  0.6570],
          [ 0.9894,  0.4121, -0.5440],
          [-1.0000, -0.5366,  0.4202]],

         [[ 0.9906,  0.6503, -0.2879],
          [-0.9614, -0.7510,  0.1499],
          [ 0.9129,  0.8367,  0.4987]]],


        [[[-0.9589, -0.2794,  0.6570],
          [ 0.9894,  0.4121, -0.5440],
          [-1.0000, -0.5366,  0.4202]],

         [[ 0.9906,  0.6503, -0.2879],
          [-0.9614, -0.7510,  0.1499],
          [ 0.9129,  0.8367,  0.4987]]]])

Link to the documentation containing tensor operations:

https://pytorch.org/docs/stable/torch.html

In [37]:
import numpy as np

In [39]:
#How to make multi-dimensional arrays in numpy, very similar to pytorch
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [40]:
#Pytorch is interoperable with numpy, so there are many ways to use numpy objects w/ pytorch
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [41]:
#Note the differences in the types of these objects
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [43]:
#Go from tensor back to numpy:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

If you can work with multi-dimensional data with numpy, why use pytorch??

1. The ability to automatically compute gradients w.r.t tensors
2. GPU support: much more efficient and powerful to use tensors than numpy arrays

In [44]:
#Saving your notebook to Jovian:

import jovian

<IPython.core.display.Javascript object>

In [47]:
jovian.commit(project = '01-tensors-basics', filename='1-basics.ipynb')

<IPython.core.display.Javascript object>

[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY:[jovian] Creating a new project "danielcufino/01-tensors-basics"
[jovian] Committed successfully! https://jovian.ai/danielcufino/01-tensors-basics


'https://jovian.ai/danielcufino/01-tensors-basics'